import type { Metadata } from "next";
import { Poppins, Open_Sans } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "./components/Navbar";
import { AppToaster } from "./components/popup/AppToaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600", "700", "800"],
  variable: "--font-display",
})

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-body",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.className} ${poppins.variable} ${openSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          enableColorScheme
        >
          <Navbar />
          {/* Global toaster so any page can trigger toast popups */}
          <AppToaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
